#!/usr/bin/node

const path = require('path');
const { runCommands, PATHS } = require('../utils.js');

const main = () => {
	setup();
};

const ARTIFACTS_CRYPTO_CONFIG = path.join(PATHS.ARTIFACTS, '/crypto-config');
const CONFIGS_CRYPTO_CONFIG = path.join(PATHS.CONFIGS, '/crypto-config');

/**
// # Generate networks peer organizations
// cryptogen extend --input=$PWD/artifacts/crypto-config --config=$PWD/configs/crypto-config/peers.yaml
 */
const setup = () => {
	let commands = [
		`cryptogen extend --input=${ARTIFACTS_CRYPTO_CONFIG} --config=${path.join(
			CONFIGS_CRYPTO_CONFIG,
			'magnetocorp-digibank-peers.yaml'
		)}`,
	];

	try {
		runCommands(commands);
		console.log('Artifacts generated');
	} catch (err) {
		console.log(err);
	}
};

main();
