#!/usr/bin/node

const path = require('path');
const { Command } = require('commander');
const { runCommands, cleanFiles, PATHS } = require('./utils.js');

const main = () => {
	const program = new Command();

	program.option('-c --clean', 'cleans the output of this script');
	program.parse(process.argv);

	if (program.opts().clean) {
		clean();
	} else {
		setup();
	}
};

const ARTIFACTS_PEER = path.join(
	PATHS.ARTIFACTS,
	'peers/',
	'magnetocorp.com/',
	'magnetocorp-dev-peer/'
);

const setup = () => {
	let commands = [`peer node start`];

	try {
		runCommands(commands);
	} catch (err) {
		console.log(err);
	}
};

/**
// # Cleaning up the orderer genesis block and its inspection
 */
const clean = () => {
	try {
		cleanFiles([ARTIFACTS_PEER]);
		console.log('Artifacts cleaned');
	} catch (err) {
		console.log(err);
	}
};

main();
