#!/usr/bin/node

const path = require('path');
const { Command } = require('commander');
const { runCommands, PATHS } = require('./utils.js');

const main = () => {
	const program = new Command();

	program.parse(process.argv);

	setup();
};

const ARTIFACTS_CONFIGTX = path.join(PATHS.ARTIFACTS, '/configtx');
const ARTIFACTS_CONFIGTX_CHANNEL_GENESIS = path.join(
	ARTIFACTS_CONFIGTX,
	'magnetocorp-channel-genesis.block'
);

const CERTIFICATES = {
	ORDERER_TLS_ROOTCERT_FILE: path.join(
		PATHS.ARTIFACTS,
		'crypto-config/ordererOrganizations/magnetocorp.com/orderers/orderer.magnetocorp.com/msp/tlscacerts/tlsca.magnetocorp.com-cert.pem'
	),
	CORE_PEER_TLS_KEY_FILE: path.join(
		PATHS.ARTIFACTS,
		'crypto-config/peerOrganizations/magnetocorp.com/peers/magnetocorp-dev-peer/tls/server.key'
	),
	CORE_PEER_TLS_CERT_FILE: path.join(
		PATHS.ARTIFACTS,
		'crypto-config/peerOrganizations/magnetocorp.com/peers/magnetocorp-dev-peer/tls/server.crt'
	),
};

/**
// # Generate the orderer genesis block and its inspection
// peer channel join \
//  -b ${ARTIFACTS_CONFIGTX_CHANNEL_GENESIS} \
//  -o 127.0.0.1:7050 \
//  --tls --cafile ${ORDERER_TLS_ROOTCERT_FILE} \
//  --clientauth --certfile ${CORE_PEER_TLS_CERT_FILE} \
//  --keyfile ${CORE_PEER_TLS_KEY_FILE}
// pushd $PWD/artifacts/configtx
// configtxgen -inspectChannelCreateTx magnetocorp-channel.tx > magnetocorp-channel-info.json
// popd
 */
const setup = () => {
	let commands = [
		`peer channel join` +
			` -b ${ARTIFACTS_CONFIGTX_CHANNEL_GENESIS}` +
			` -o 127.0.0.1:7050` +
			` --tls --cafile ${CERTIFICATES.ORDERER_TLS_ROOTCERT_FILE}` +
			` --clientauth --certfile ${CERTIFICATES.CORE_PEER_TLS_CERT_FILE}` +
			` --keyfile ${CERTIFICATES.CORE_PEER_TLS_KEY_FILE}`,
	];

	try {
		runCommands(commands);
		console.log('Artifacts generated');
	} catch (err) {
		console.log(err);
	}
};

main();
